### ISSUE TITLE
Code style: Spaces instead of tabs

### ISSUE THREAD

**Issue by dominikandreas** [ai-tor/VPilot#11]
I'd suggest using 4 spaces instead of a tab since it's the official standard for python code ([PEP 8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces))

This would make it easier for others to change things and submit pull requests and prevents interpreter errors in the future (python 3 for example doesn't allow mixing tabs and spaces)

Thanks for your work, I really appreciate it!

**Comment by aitorzip** [comment]
Sure thing! I will redactor that in the next commit :)
