### ISSUE TITLE
Cannot retrive the image in drive.py

### ISSUE THREAD

**Issue by yanpanlau** [ai-tor/VPilot#12]
Hi, First of all. Great work!

I successfully installed DeepGTAV and VPilot. When I run drive.py, I can teleport the human into a new driving scene, so the connection is doing properly.

However, I am trying to extract the image screen. Suppose this code should do the job:

```image = frame2numpy(message['frame'], (320,160))```

However, the image simply return a bunch of zeros instead. Would you please let me know how to fix the problem?

**Comment by aitorzip** [comment]
Hi @yanpanlau 

Thanks for your compliments! :)

Make sure you are running GTAV in windowed mode and it is maximized

**Comment by yanpanlau** [comment]
No luck yet...I tried windowed mode / window borderless mode / fullscreen mode, and different resolution (from maximum to 800x600) but the image still show 0....

**Comment by aitorzip** [comment]
Set the resolution to 800x600 and windowed mode and then try to save the image with `cv2.imwrite('result.png', image)`, you can also try to do something like `np.max(image)` just to check if really everything is 0

**Comment by yanpanlau** [comment]
I tried the method you suggest but I 100% confirm the image is black and the value of the array is zero. 

So test I did:

1) Try Alt-Enter to switch between Full Screen vs 800x600 window, doesn't work
2)  In drive.py, change the steering to 1.0, I can see the car turn right, so I confirm the tcp communication OK. [As I can send message]
3) I print the information in _recvall() function, it returns two array bytes. The first one is byte size 153,600, which I think is the screen size (320x160x3), They are all \x00
4) Here is the dump of _recvall() function

```b'{"commands": {"brake": 0.0, "steering": 1.0, "throttle": 1.0}}'
Now calling _recvall()
b'\x00X\x02\x00'
b'\x00X\x02\x00'
Now print out size = struct.unpack('I', data)[0])
The size of the data is 153600
Now calling _recvall()
b'\x02\x00\x00\x00'
b'\x02\x00\x00\x00'
Now print out size = struct.unpack('I', data)[0])
The size of the data is 2
np.max(image) of the image array is 0
```

I also attached the log file for your reference



[deepgtav.txt](https://github.com/ai-tor/VPilot/files/990047/deepgtav.txt)
[ScriptHookV.txt](https://github.com/ai-tor/VPilot/files/990048/ScriptHookV.txt)
[asiloader.txt](https://github.com/ai-tor/VPilot/files/990049/asiloader.txt)

**Comment by yanpanlau** [comment]
I deep dive into the deepgtav.log and there is an error "Error receiving message length: 10054" or Error receiving message length: 10053". I wonder if that is causing the problem? Do I need to modify any tcp/ip or routers or firewall setting to get the tcp connection works? Thanks (I am running GTA V/DeepGTAV in windows 10, and running VPilot in Ubuntu 16.04). Both computers are connected via a router.

**Comment by cpgeier** [comment]
Did you resolve the issue? I'm having the same problem, although it may be a problem with DeepGTAV not VPilot: https://github.com/ai-tor/DeepGTAV/issues/45

**Comment by cpgeier** [comment]
I was able to solve my issue by changing `	hWnd = ::FindWindow(NULL, "Grand Theft Auto V");` on line 14 of ScreenCapturer.cpp to `	hWnd = ::FindWindow(NULL, "Compatitibility Theft Auto V");`. Of course you can change it to anything you want, but the point is that I guess the win32 window screen capture doesn't work for some systems running GTAV, so renaming the window to a window that doesn't exist fixes the issue by capturing the entire screen. Once I recompiled the project in Visual Studio, I was able to view screenshots from the game with the code found in dataset.py.

Just remember the game must be full screen (Alt-Enter) after you make this change to capture the game.

The DeepGTAV.asi file I made can be found here:
https://drive.google.com/open?id=0B7gX17GpTrgxai0xai1jVGE1OGs

**Comment by aitorzip** [comment]
Solved in last DeepGTAV commit. Looks like Windows 10 somehow fails to find windows, we use full-screen now for compatibility with Windows 7 and 10 versions
