### ISSUE TITLE
The game got frozen in reinforcement mode

### ISSUE THREAD

**Issue by yanzheng9527** [ai-tor/VPilot#7]
The game works fine in supervised mode. And it is very slow in reinforcement mode. But when I close my server, it works fluently again. Is it because my computer sucks?

I am using i7-4770 CPU and Intel HD Graphics 4600 GPU.

Here below is my log.

/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/yanzheng/PycharmProjects/GTADriving/drive.py /Users/yanzheng/PycharmProjects/GTADriving/model.h5 8000 320 160
Using TensorFlow backend.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Started server
GTAV connected
/Users/yanzheng/PycharmProjects/GTADriving/drive.py:61: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if (img == None): break
Sent commands array('f', [0.22991320490837097, -0.0930078998208046])
Received reward
0.0
Sent commands array('f', [0.2596898376941681, -0.07997480034828186])
Received reward
0.0
Sent commands array('f', [0.25979164242744446, -0.07992687076330185])
Received reward
0.0
Sent commands array('f', [0.2598057687282562, -0.07992041856050491])
Received reward
0.0

**Comment by aitorzip** [comment]
Hi @yanzheng0000, 

Yes, I am afraid that's the issue. You are running tensorflow in your CPU (your GPU is doing nothing here), which is quite good but not enough to run the VPilot CNN in real time. The game blocks until it receives the commands from VPilot, which unfortunately come quite slowly. :(

**Comment by yanzheng9527** [comment]
Hi,
The laptop running VPilot is 2.7 GHz Intel Core i5 and Intel Iris Graphics 6100 1536 MB.
The computer running GTA V is  i7-4770 CPU and Intel HD Graphics 4600 GPU.

1.Do you mean the laptop or the computer is too weak? 
2.Should I use a computer to run VPilot and install tensorflow-GPU rather than tensorflow?

Thanks,
Yan

**Comment by aitorzip** [comment]
Hi! 

Both of them have quite low specs, but the important one is the one running VPilot. You won't be able to use Tensorflow gpu on it because you need an Nvidia graphics card
