### ISSUE TITLE
cannot open dataset.pz file

### ISSUE THREAD

**Issue by Yale323** [ai-tor/VPilot#8]
Thanks for your sharinig.
I try the dataset mode, it work well. 
But I cannot open the stored data file dataset.pz .
Is it a correct file format or it need the special tool to open it?

**Comment by aitorzip** [comment]
Hi @Yale323, 

It has to be opened from Python using Pickle and gzip, very much the same way it is created. 

Pickle is a Python format, so there are no external tools to open it I believe. 

See Client.py to see how these libraries work, there is plenty of documentation in the official Python docs too.

**Comment by Yale323** [comment]
@ai-tor Thanks for your answer.

**Comment by yanzheng9527** [comment]
with gzip.open('dataset.pz', 'rb',9) as f:
    file_content = f.read()
print (file_content)

I unpacked it using "gzip.open", but I can't understand those parameters. In the old DeepGTAV, I can understand the meaning of those numbers in dataset... 

How to use dataset.pz?
